Nonlinearelastic
GCMLab/GCMLab-FEM pull request #77
Opened 2023-04-20 21:19 UTC by brunaccampos

## What?
Add a nonlinear elastic constitutive model.
## Why?
To expand the functionalities of the code in terms of material models.
## How?
By using the recently introduced function pointers, the user can define the formats of the tangent stiffness matrix, constitutive matrix, and strain computation to simulate a nonlinear elastic behavior.
## Testing?
Plate_NLelastic (Config Files)
## Anything Else?
For the first step of the first iteration, the stiffness matrix, constitutive matrix, and strain matrix are computed as in the linear elastic case by default. For the following iterations, the function pointers defined by the users redirect the code to the correspondent functions. In addition, now the strain from the previous step needs to be stored so that the constitutive matrix of the current step can be computed.

2023-04-27 14:16 UTC, b3gee commented on Functions/Assembly/getStrain_NLelastic.m
D matrix is not currently evaluated for nodal or cell center cases.

2023-04-27 14:36 UTC, b3gee requested changes
- [x] Reviewed function(s): Plate_NLelastic, getK, getK_NLelastic, getStrain, getStrain_NLelastic, getD, getD_NLelastic, main_nonlinear 
- [x] Ran test case(s): RunTests - ! **Failure in many tests**, seems to be related to stress calculations
* Purpose of the code: 
   - To add a non-linear material model
* Notes on implementation: 
   - getStrain_NLelastic currently does not define the D matrix for non-
* Notes on legibility and style: 
   * Please update the header of getStrain_NLelastic 
* Notes on maintainability: 
   * For future implementation: We should consider a systematic naming approach to material models, perhaps a library with naming conventions.
* Suggested test cases: 
   * Perhaps a quasi-1D bar with a force-displacement curve? The stresses in the case Plate_NLelastic look good.

2023-05-03 16:14 UTC, brunaccampos commented
Updates:
- getStrain updated to compute nonlinear D matrix for all cases (nodal, center, L2projection)
- header of getD_NLelastic updated
- RunTests now working
- new function added to plot load-displacement curve, along with the correspondent tags and setDefaults commands
- MasterConfigFile updated with tags for load-displacement plot for future reference
- 2D plate example updated to a 1-element problem with a shear load
- 1D bar example added

Note:
- plot for displacement vs. load is closed as the simulation is over (no time to verify/look at the plot). Maybe in the future consider removing 'close all' line from RumSim
- evaluate need to add a description of the model and the obtained load-displacement curve figures to the Wiki page

2023-05-11 17:21 UTC, b3gee approved these changes
- [x] Reviewed function(s): getK_NLelastic, getStrain_NLelastic, getD_NLelastic, plotLoadVsDispl
- [x] Ran test case(s): RunTests,  NLElastic_1DBar, NLElastic_2DPlate
* Purpose of the code: 
* Notes on implementation: N/A
* Notes on legibility and style: N/A
* Notes on maintainability: N/A
* Suggested test cases: N/A

2023-05-11 17:22 UTC, merged