Thermoelasticity
GCMLab/GCMLab-FEM pull request #89
Opened 2023-09-07 14:38 UTC by brunaccampos

## What?
Add a new feature to the code that deals with linear thermoelasticity problems.
## Why?
To solve coupled problems in terms of mechanical and thermal variables (displacement and temperature).
## How?
A new material model was added to the code. Changes were made to accommodate the coupled nature of the problem.
## Testing?
RunTests works with the new framework, and a new Thermoelastic Test was added.
## Anything Else?
Current test encompasses only a manufactured solution with essential BCs. In the future, consider adding another example. Also, the current verification consists in checking the error between the FEM and exact solution and the sum of the external forces vector. Consider adding a mesh convergence study.

2023-09-19 19:28 UTC, SaeedHatefi commented
- [x] Reviewed function(s): RunSim, RunTests, ThermoElastic_Dirichlet, RunThermoelasticTest, Thermoelasticity_check, main_nonlinear, Post-processing m files, cleanInput, getK_coupled, getFext_coupled, getStrainFlux_THLE1, getStrain, getFlux_TH1
- [x] Ran test case(s): RunSim, RunTests
* Purpose of the code: To add a coupled feature to the code by solving a steady-state thermoelastic problem
* Notes on implementation: The code works well for thermal elastic manufactured problem. However, there are some suggestions and issues needed to be addressed before merging:
   *  The ThermoElasticConfigFile.m in the folder Config Files does not run and there is an error. I would suggest to create a config file for thermo elastic problem.
   *  Consider to test the code for 
   *  When the state for the calculation of stress/strain/flux is changed into 'nodal' and 'center', we will see an error in the code.
   *  For the added test case, when the temperature at the boundary is considered as ./1, the result will not change with the case that the thermal BC is as ./1000. Also, the amount of flux is very low (in the order of e-17). I would appreciate it if you could have a comment about this.
   *  There is a great effort to add gradT in the post processing for thermoelastic case. I would suggest to add gradT in the post processing of diffusion problem (write2vtk_dfsn).
   *  Consider to calculate gradT in getFlux_TH1.m
   * Consider to test the thermoelastic code for different mesh formats other than BuildMesh_structured function

* Notes on legibility and style:
   * Consider to unify NodeSets with NodeSetsCoupled (if possible)
   * Consider to add the word "coupled" in the comment related to the function NodeDOFs line 33: Mixed --> Coupled problem
   * The idea of definition variables as ..._mech and ..._sca is nice. However, I would suggest to unify all the variables according to this definition. For example, in getStrainFlux_THLE1.m lines 100 and 101, I would suggest A_mech and A_sca
   * Consider to modify the function header for getK_coupled and add yourself in the Acknowledgement
   * Consider to call "getK_THLE1" in the setMaterialModel instead of getK_LE1 (line 25). By this way, in the Newton-Raphson loop, we will call "getK_THLE1" instead of getK_LE1 (The same procedure as diffisuin problem but just for the steady state case)
   * getFint_ini is correct in the case of linearity, but we should change it in the next steps for adding the nonlinearity (No need to be modified at this branch)
   * In main_nonlinear line 263, the outputs of the feval function can be modified according to the type of problem (1, 2 , 3) (The same procedure as the lines 119-131)
* Notes on maintainability: N/A
* Suggested test cases: N/A

2023-09-19 19:29 UTC, SaeedHatefi requested changes
- [x] Reviewed function(s): RunSim, RunTests, ThermoElastic_Dirichlet, RunThermoelasticTest, Thermoelasticity_check, main_nonlinear, Post-processing m files, cleanInput, getK_coupled, getFext_coupled, getStrainFlux_THLE1, getStrain, getFlux_TH1
- [x] Ran test case(s): RunSim, RunTests
* Purpose of the code: To add a coupled feature to the code by solving a steady-state thermoelastic problem
* Notes on implementation: The code works well for thermal elastic manufactured problem. However, there are some suggestions and issues needed to be addressed before merging:
   *  The ThermoElasticConfigFile.m in the folder Config Files does not run and there is an error. I would suggest to create a config file for thermo elastic problem.
   *  Consider to test the code for 
   *  When the state for the calculation of stress/strain/flux is changed into 'nodal' and 'center', we will see an error in the code.
   *  For the added test case, when the temperature at the boundary is considered as ./1, the result will not change with the case that the thermal BC is as ./1000. Also, the amount of flux is very low (in the order of e-17). I would appreciate it if you could have a comment about this.
   *  There is a great effort to add gradT in the post processing for thermoelastic case. I would suggest to add gradT in the post processing of diffusion problem (write2vtk_dfsn).
   *  Consider to calculate gradT in getFlux_TH1.m
   * Consider to test the thermoelastic code for different mesh formats other than BuildMesh_structured function

* Notes on legibility and style:
   * Consider to unify NodeSets with NodeSetsCoupled (if possible)
   * Consider to add the word "coupled" in the comment related to the function NodeDOFs line 33: Mixed --> Coupled problem
   * The idea of definition variables as ..._mech and ..._sca is nice. However, I would suggest to unify all the variables according to this definition. For example, in getStrainFlux_THLE1.m lines 100 and 101, I would suggest A_mech and A_sca
   * Consider to modify the function header for getK_coupled and add yourself in the Acknowledgement
   * Consider to call "getK_THLE1" in the setMaterialModel instead of getK_LE1 (line 25). By this way, in the Newton-Raphson loop, we will call "getK_THLE1" instead of getK_LE1 (The same procedure as diffisuin problem but just for the steady state case)
   * getFint_ini is correct in the case of linearity, but we should change it in the next steps for adding the nonlinearity (No need to be modified at this branch)
   * In main_nonlinear line 263, the outputs of the feval function can be modified according to the type of problem (1, 2 , 3) (The same procedure as the lines 119-131)
* Notes on maintainability: N/A
* Suggested test cases: N/A

2023-09-19 21:31 UTC, brunaccampos commented
Answering the requests:

  - The ThermoElasticConfigFile.m in the folder Config Files does not run and there is an error. I would suggest to create a config file for thermo elastic problem.
_Indeed this file does not work; we decided to use a test file instead. This file has been deleted; the verification of the code for the coupled problem should be done using RunTests._
  - When the state for the calculation of stress/strain/flux is changed into 'nodal' and 'center', we will see an error in the code.
_Fixed_
  - For the added test case, when the temperature at the boundary is considered as ./1, the result will not change with the case that the thermal BC is as ./1000. Also, the amount of flux is very low (in the order of e-17). I would appreciate it if you could have a comment about this.
_I'm not sure I see this flux of very low order; when visualizing in Paraview, maximum flux is 0.15. Does this low order appear somewhere in the results in the code?_
  - There is a great effort to add gradT in the post processing for thermoelastic case. I would suggest to add gradT in the post processing of diffusion problem (write2vtk_dfsn).
_Done_
  - Consider to calculate gradT in getFlux_TH1.m
_Done_
  - Consider to test the thermoelastic code for different mesh formats other than BuildMesh_structured function
_The change necessary to run the thermoelastic problem was made in the number of DOFs per node, not in the mesh per se. That being said, the code indeed needs to be verified for Hypermesh files. Maybe I can do that in a later branch, after the node sets will be working?_
- Consider to unify NodeSets with NodeSetsCoupled (if possible)
_Done_
- Consider to add the word "coupled" in the comment related to the function NodeDOFs line 33: Mixed --> Coupled problem
_Done_
- The idea of definition variables as ..._mech and ..._sca is nice. However, I would suggest to unify all the variables according to this definition. For example, in getStrainFlux_THLE1.m lines 100 and 101, I would suggest A_mech and A_sca
_Done_
- Consider to modify the function header for getK_coupled and add yourself in the Acknowledgement
_Done_
- Consider to call "getK_THLE1" in the setMaterialModel instead of getK_LE1 (line 25). By this way, in the Newton-Raphson loop, we will call "getK_THLE1" instead of getK_LE1 (The same procedure as diffisuin problem but just for the steady state case)
_Done_
- getFint_ini is correct in the case of linearity, but we should change it in the next steps for adding the nonlinearity (No need to be modified at this branch)
_Noted_
- In main_nonlinear line 263, the outputs of the feval function can be modified according to the type of problem (1, 2 , 3) (The same procedure as the lines 119-131)
_The switch function in line 119 is used to compute the initial conditions, and hence it access the linear versions of the get strain functions. Since feval is more time-efficient, I would say it is better to keep it in the loop in line 263. I organized the get strain/flux/strain and flux functions to properly save all variables._

2023-09-26 19:58 UTC, SaeedHatefi approved these changes

2023-09-26 19:58 UTC, merged