Nl thermal
GCMLab/GCMLab-FEM pull request #90
Opened 2023-10-17 02:05 UTC by GZingaro

## What? The convergence rate of the NR algorithm is not quadratic for linear elements for the Abaqus benchmark problem. 
## Why? Ensure NLTH1 is converging as expected before merging into develop branch. 
## How? Check into the implementation of nonlinear transient heat diffusion (NLTH1). 
## Testing? Evaluated using Abaqus Benchmark problem in Meeting Notes. Uploaded NLTH1_ABAQUS_Config.m and NLTH1_ABAQUS_Mesh.xlsx files to the configuration folder. 
## Anything Else? N/A

2023-11-13 18:56 UTC, SaeedHatefi requested changes
- [x] Reviewed function(s): RunSim, RunTests, NLThermal1, main_nonlinear, write2vtk_dfsn, setMaterialModel, getK_NLTH1, getFlux_TH1, getD_NLTH1
- [x] Ran test case(s): RunSim, RunTests
* Purpose of the code: To add a nonlinearity feature to the code of thermal transient by solving a benchmark from ABAQUS
* Notes on implementation: The code works well for the current setup of the config file. However, there are some suggestions and issues needed to be addressed before merging:
   *  Consider to test the code for the cases mentioned in the Suggested test cases section.
   *  For the case of orthotropic, there is an error when it is tried to run the code. Also, for this case, getFlux function should be modified based on the conductivity in x and y direction
* Notes on legibility and style:
   * Consider to move NLTH1_ABAQUS_Mesh.xlsx file to Mesh Files folder
   * It seems that the files getK_TH3.m and getD_TH3.m should be removed since they are not being used in the code.
   * Suggest that to define a feval function for the definition of Constitutive Law in getK_NLTH1 instead of direct call of the fucntion getD_NLTH1. Function getK_TR2 can be a good reference for this.
   * Suggest to have a comment about the options we can have for the definition of getFlux: 1: We can define another getFlux for nonlinear thermal case or 2: we can modify the current getFlux_TH1 function.
   * In getFlux_TH1, I suggest to define a feval function instead of directly calling getD_TH1. For example, getStrain_ST1 is using feval function.
   * In getK_NLTH1, consider to rename the parameter beta to alpha because alpha is a time integration parameter. By this change, the material parameter should be rename to another thing.
   * In main_nonlinear.m, there are some debugging lines for plotting the residual values. It is a great job. I suggest to remove these lines after testing the code for the metioned tests
* Notes on maintainability: N/A
* Suggested test cases: N/A
   *  Consider to test the code for the case that we have body force. The goal is to check the residual force definition and the convergence rate for this case.
   *  Consider to test the code for the case that we have extenrnal flux. So, we will have a Neumann BC in this case. The goal is to check the residual force definition and the convergence rate for this case.
   *  Consider to test the code for Orthotopic case when the conductivity in x and y directions are different. In this case, we should have some modifications for getFlux function.

2023-11-15 04:21 UTC, GZingaro commented
> * [x]  Reviewed function(s): RunSim, RunTests, NLThermal1, main_nonlinear, write2vtk_dfsn, setMaterialModel, getK_NLTH1, getFlux_TH1, getD_NLTH1
> * [x]  Ran test case(s): RunSim, RunTests
> 
> * Purpose of the code: To add a nonlinearity feature to the code of thermal transient by solving a benchmark from ABAQUS
> * Notes on implementation: The code works well for the current setup of the config file. However, there are some suggestions and issues needed to be addressed before merging:
>   
>   * Consider to test the code for the cases mentioned in the Suggested test cases section. UPDATED: Ran manufactured solution for orthotropic transient diffusion. Code has been verified. Remaining tasks: run simulation with Neumann boundary conditions, and verify the heat flux. 

>   * For the case of orthotropic, there is an error when it is tried to run the code. Also, for this case, getFlux function should be modified based on the conductivity in x and y direction. UPDATE: Updated field "alpha2". Runs correctly and has been pushed. 
> * Notes on legibility and style:
>   
>   * Consider to move NLTH1_ABAQUS_Mesh.xlsx file to Mesh Files folder. UPDATE: Complete.
>   * It seems that the files getK_TH3.m and getD_TH3.m should be removed since they are not being used in the code. UPDATE: Complete.
>   * Suggest that to define a feval function for the definition of Constitutive Law in getK_NLTH1 instead of direct call of the fucntion getD_NLTH1. Function getK_TR2 can be a good reference for this. UPDATED: Complete. 
>   * Suggest to have a comment about the options we can have for the definition of getFlux: 1: We can define another getFlux for nonlinear thermal case or 2: we can modify the current getFlux_TH1 function. UPDATED: Created and modified GetFlux_TH1 for GetFlux_NLTH1. Verify is running correctly as the inputs to GetD in the function have been modified.
>   * In getFlux_TH1, I suggest to define a feval function instead of directly calling getD_TH1. For example, getStrain_ST1 is using feval function. UPDATE: Complete. 
>   * In getK_NLTH1, consider to rename the parameter beta to alpha because alpha is a time integration parameter. By this change, the material parameter should be rename to another thing. UPDATE: Renamed to k. 
>   * In main_nonlinear.m, there are some debugging lines for plotting the residual values. It is a great job. I suggest to remove these lines after testing the code for the mentioned tests. UPDATE: Complete.
> * Notes on maintainability: N/A
> * Suggested test cases: N/A
>   
>   * Consider to test the code for the case that we have body force. The goal is to check the residual force definition and the convergence rate for this case. UPDATE: Complete. 
>   * Consider to test the code for the case that we have extenrnal flux. So, we will have a Neumann BC in this case. The goal is to check the residual force definition and the convergence rate for this case. UPDATE: Ongoing task. 
>   * Consider to test the code for Orthotopic case when the conductivity in x and y directions are different. In this case, we should have some modifications for getFlux function. UPDATED: Complete.

2023-11-15 21:15 UTC, GZingaro commented
What? Requesting a review of the nonlinear transient thermal branch. 

Why? Check the implementation of the nonlinear transient thermal branch before merging into the develop branch.

How? Check into the implementation of nonlinear transient heat diffusion (NLTH1).

Testing? All previous comments have been addressed. Please run a nonlinear diffusion test with Neumann boundary conditions to verify the code is running correctly. Additionally, please check the getFlux_NLTH1 as the inputs to the constitutive law have been modified since the last revision. 

Anything Else? N/A

2023-11-27 19:29 UTC, SaeedHatefi approved these changes

2023-11-28 00:05 UTC, merged